// Generated by CoffeeScript 1.9.3
(function() {
  define(['react'], function(React) {
    var Push, div, h4, img, p, ref;
    ref = React.DOM, div = ref.div, h4 = ref.h4, p = ref.p, img = ref.img;
    Push = React.createFactory(React.createClass({
      displayName: 'Push',
      changeText: function(event) {
        if (event.target.value.length > 0) {
          return this.setState({
            keyval: event.target.value,
            okbtnclass: 'button-primary',
            okbtnclk: this.fire
          });
        } else {
          return this.setState({
            keyval: '',
            okbtnclass: 'disabled',
            okbtnclk: null
          });
        }
      },
      clear: function() {
        return this.setState({
          keyval: '',
          okbtnclass: 'disabled',
          okbtnclk: null
        });
      },
      getInitialState: function() {
        return {
          keyval: '',
          okbtnclass: 'disabled',
          okbtnclk: null
        };
      },
      fire: function() {
        return this.props.f({
          clientId: this.state.keyval
        });
      },
      render: function() {
        return div({}, [
          div({
            key: "api-cont"
          }, [
            React.DOM.label({
              key: 'label',
              htmlFor: 'apikey'
            }, "Client Key"), React.DOM.input({
              key: 'field',
              className: 'u-full-wdth',
              id: 'apikey',
              ref: 'apikey',
              value: this.state.keyval,
              onChange: this.changeText
            })
          ]), div({
            key: "sig-buttons",
            className: "signature-buttons"
          }, [
            React.DOM.button({
              key: 'clrbtn',
              onClick: this.clear
            }, "Clear"), React.DOM.button({
              key: 'okbtn',
              className: this.state.okbtnclass,
              onClick: this.state.okbtnclk
            }, "Ok")
          ])
        ]);
      }
    }));
    return React.createFactory(React.createClass({
      displayName: 'ReceiveBacon',
      render: function() {
        return Push({
          f: this.props.buttonPress
        });
      }
    }));
  });

}).call(this);
