// Generated by CoffeeScript 1.9.3
(function() {
  define(['jquery', 'react', 'spinner'], function($, React, Spinner) {
    return React.createFactory(React.createClass({
      displayName: 'Spinner',
      opts: {
        lines: 9,
        length: 30,
        width: 14,
        radius: 40,
        scale: 0.25,
        corners: 1,
        color: '#333',
        opacity: 0.1,
        rotate: 0,
        direction: 1,
        speed: 2.5,
        trail: 47,
        fps: 20,
        zIndex: 2e9,
        className: 'spinner',
        top: '75%',
        left: '50%',
        shadow: false,
        hwaccel: false,
        position: 'absolute'
      },
      componentDidMount: function() {
        var sp;
        sp = new Spinner(this.opts);
        return sp.spin(this.refs.spin.getDOMNode());
      },
      render: function() {
        return React.DOM.div({
          ref: "spin",
          key: 'spinspin'
        });
      }
    }));
  });

}).call(this);
